---
- name: Configuring Allow Access
  template:
    src: "hosts.allow.j2"
    dest: "/etc/hosts.allow"
    group: "root"
    owner: "root"
    mode: "u=rw,g=r,o=r"

- name: Configuring Deny Access
  template:
    src: "hosts.deny.j2"
    dest: "/etc/hosts.deny"
    group: "root"
    owner: "root"
    mode: "u=rw,g=r,o=r"
